### ISSUE TITLE
Java DB Location

### ISSUE THREAD

**Issue by JADM** [LouisBarranqueiro/ZPareo#2]
I get a prompt when running saying that Java DB location is not set correctly. Any ideas about what can I be doing wrong? I am using NetBeans as IDE. MySQL already running and with the database on it.
I found in the dao.properties file the connection details which I modified accordingly but no changes.
Can you tell me where the DB connection is being managed &/or created? 

Thanks in advance
Nice program, thanks for sharing

**Comment by LouisBarranqueiro** [comment]
👋 @JADM, `dao.properties` contains database configuration, so if it still not work, make sure information are correct by using a mysql client to test your configuration.
